version: "3.4"

services:
  postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - authentik-database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: postgres
      POSTGRES_DB: authentik

  redis:
    image: redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - authentik-redis:/data

  auth2:
    image: ghcr.io/goauthentik/server:2023.5.3
    restart: unless-stopped
    command: server
    networks:
      - global_net
    environment:
      AUTHENTIK_SECRET_KEY: ${SECRET_KEY}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - authentik-media:/media
      - authentik-templates:/templates
    #ports:
    #  - "9000:9000"
    #  - "9443:9443"
    depends_on:
      - postgresql
      - redis
      - ldap
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.auth2.entrypoints=https'

  worker:
    image: ghcr.io/goauthentik/server:2023.5.3
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: ${SECRET_KEY}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik-media:/media
      - authentik-certs:/certs
      - authentik-templates:/templates
    depends_on:
      - postgresql
      - redis
      - ldap

  ldap:
    image: nitnelave/lldap:v0.4.3
    restart: unless-stopped
    networks:
      - global_net
      - ldap_net
    #ports:
      # For LDAP
      #- "3890:3890"
      # For the web front-end
      #- "17170:17170"
    volumes:
      - "lldap_data:/data"
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Paris
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS}
      - LLDAP_LDAP_BASE_DN=dc=thetoto,dc=fr
      #- LLDAP_DATABASE_URL=postgres://postgres:${PG_PASS}@postgresql/lldap # Use sqlite if not defined
    depends_on:
      - postgresql
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ldap.entrypoints=https'

volumes:
  authentik-database:
  authentik-redis:
  authentik-certs:
  authentik-media:
  authentik-templates:
  lldap_data:

networks:
  global_net:
    external: true
  ldap_net: