version: "3.4"

services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    environment:
      - CONTAINERS=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    image: traefik:2.10.1
    restart: unless-stopped
    volumes:
      - ./traefik/acme.json:/acme.json
      - ./traefik/data:/data
    networks:
      - traefik_net
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.middlewares=authelia@docker'
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    extra_hosts:
      - host.docker.internal:127.0.0.1 # For net=host containers (public ip, put in env)
    ports:
      - 80:80
      - 443:443
    command:
      - '--api'
      - '--pilot.token=${PILOT_KEY}'

      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.endpoint=tcp://dockerproxy:2375'
      - '--providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service"}}.thetoto.fr`)'

        # Accept connections on :80 but redirect to :443
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'

        # Accept connections on :443
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.https.http.tls=true'
      - '--entrypoints.https.http.tls.certResolver=letsencrypt'
      - '--entrypoints.https.http.tls.domains[0].main=thetoto.fr'
      - '--entrypoints.https.http.tls.domains[0].sans=*.thetoto.fr'
      #- '--entrypoints.https.http.tls.domains[1].main=code.thetoto.fr'
      #- '--entrypoints.https.http.tls.domains[1].sans=*.code.thetoto.fr'
      #- '--entrypoints.https.http.middlewares=error-pages@docker'

      - '--certificatesResolvers.letsencrypt.acme.storage=acme.json'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare'
      # Staging
      #- '--certificatesResolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory'

      - '--log=true'
      #- '--log.level=DEBUG'
      #- '--log.filepath=/var/log/traefik.log'

      - '--accesslog.filepath=/data/access.log'
      #- '--metrics.prometheus=true'